### ISSUE TITLE
Gendering in der deutschen Übersetzung

### ISSUE THREAD

**Issue by thopanX** [schlawiner/fu-rpg-frei-und-universell#1]
Player - Spieler/in - auch wenn das etwas unelegant aussieht, ist es mir doch wichtig, nicht nur die männliche Form zu benutzen. Alternativen?

**Comment by thopanX** [comment]
Ich hab gerade eine bisschen recherchiert und finde als gut lesbare Alternative nur das Ausschreiben ohne Schrägstriche - "Spielerin" und "Spieler". 

Wir können zwischendurch wechseln oder uns für ein Geschlecht entscheiden. Oder wir schreiben "Spielerinnen und Spieler", "Spieler oder Spielerin" oder ähnlich.

-- http://www.frauenbeauftragte.uni-muenchen.de/genderkompetenz/sprache/index.html

**Comment by schlawiner** [comment]
Immer Spielerinnen und Spieler zu schreiben könnte etwas langatmig werden, aber immer wieder abwechseln könnte wiederum verwirrend sein. 
Ich habe auch schon ein Regelheft gelesen (das Brettspiel Tail Feathers von Plaid Hat Games), wo "player" einfach immer mit "she" gegendered war. Fand ich gar nicht schlecht, weil es ein kleines Gegengewicht für die unzähligen "ers" in allen anderen Texten ist. Ein Bekannte rist in einem anderen spiel auf etwas ähnliches gestoßen und fand es verwirrend/ärgerlich/ungewohnt. Aber das sehe ich eher als ein gutes Zeichen ;).
Was hältst du davon, einfach überall die weibliche Form zu nehmen und dann in der Einleitung sowas zu schreiben, was in anderen Texten auch gerne steht (aber umgekehrt): "Wir verwenden in diesem Text die weibliche Form als Ansprache, aber das umfasst Spielende aller Geschlechter."
(Erinnert mich an den genialen Twtteraccount  [@manwhohasitall](https://twitter.com/manwhohasitall) der die Welt auf ähnliche Weise verkehrt zeigt, mit Eltern- und Beautytipps für Männer, wie Frauen sie normalerweise bekommen - dort schreiben oft Männer Dinge wie "Es macht mir nichts aus, Firewoman genannt zu werden, weil in woman ja eindeutig auch 'man' drinsteckt. Mark, Firewoman")

**Comment by thopanX** [comment]
Hab nichts gegen die durchgehend weibliche Form, machen wir's so. Was hältst du davon, ab jetzt so zu verfahren und am Ende der ersten Übersetzung einmal noch von vorn durchzugehen?

**Comment by schlawiner** [comment]
Ja, ok, machen wir das so. 
Habe übrigens ein paar Milestones angelegt für die verschiedenen "Durchgänge" Rohübersetzung, Überarbeitung, Feinkorrektur. Man kann dann jedes Issue einem Milestone zuordnen und dann den Fortschritt jeder Phase als grünen Balken beobachten, indem man sich den Milestone in der Übersicht anschaut.
