### ISSUE TITLE
Rohübersetzung Kapitel 7 Anhang/Appendix

### ISSUE THREAD

**Issue by schlawiner** [schlawiner/fu-rpg-frei-und-universell#11]

**Comment by thopanX** [comment]
Fange ich mit an, wird aber einige Tage dauern.

**Comment by schlawiner** [comment]
Das macht nichts, ich habe sowieso gerade bemerkt, dass ich die gleichen Deskriptoren auch zu übersetzen habe. In Kapitel 3 (Figuren) gibt es die Liste schon einmal in Kurzform, deine im Anhang ist eine erweiterte Version mit genaueren Erklärungen jedes aufgelisteten Deskriptors. Wir sollten uns da erstmal einigen, welche Übersetzungen wir nehmen um einerseits einheitlich zu bleiben und andererseits Arbeit zu sparen. 
Bin gerade dran...

**Comment by thopanX** [comment]
Ah, verdammt, habe gerade die körperlichen Deskriptoren gemacht. Wie weit bist du?

**Comment by schlawiner** [comment]
Hab alle übersetzt - siehe 04_characters, oder hier:
Körper 
Agil, Beidhändig, Blond, Pelzig, Selbstbräuner-Orange, Gutaussehend, Gewaltig, Übergewichtig, Schwache Konstitution, Flink, Rasiermesserscharfe Krallen, Klein, Langsam, Stark, Hochgewachsen, Dünn, Hässlich, Vitalität (Vigour), Schwach.

Geist: Zerstreut, Belesen, Computerfreak, Schwer von Begriff, Einfühlsam, Konzentriert, Querdenkerin, Mathematikerin, Aufmerksam, Rednerin, Langsam, Taktikerin, Ungebildet, Weise, Geistreich.

Stärke: Akrobatik, Okkultes Geheimwissen, Mut, Fahren, Fechten, Gutes Gedächtnis, Jagd/Jagen?, Scharfe Augen, Linguistik, Magie, Medizin, Fieser Biss, Reich, Ringkampf.

Schwäche: Blind, Mutig, Ungeschickt, Gierig, Unmenschliches Aussehen, Fehlendes Bein, Alt, Arm, Sieht schlecht, Primitiv, Intensiver Geruch, Gesucht, Jung.

**Comment by thopanX** [comment]
Bin zu zwei Dritteln durch, muss danach aber noch mal drüber. Ich hab die Erklärungen im ersten Lauf abgekürzt und nicht immer "great for" genommen, sondern "Vorteil beim" und "Nachteil beim". Mal sehen, ob ich das noch ändere.

Die Beschreiber hab ich fett formatiert, weil ich das besser finde, kann ich aber auch wieder rückgängig machen, falls das der einzige Ort im Dokument sein sollte.

**Comment by thopanX** [comment]
Ich hab wenige Begriffe, die ich anders übersetzen würde:

Für Agil = beweglich.

Slow = langsam im Kopf

Linguistics = Sprachwissenschaften

**Comment by schlawiner** [comment]
Beweglich und Sprachwissenschaften finde ich gut!
Was Slow angeht: weiß nicht, ob eine so genaue Abgrenzung nötig ist, denn eigentlich erklärt sich das "im Kopf" schon durch die Art des Beschreibers - es ist quasi implizit. Auf seinem "Charakterbogen", haha, hat man ja dann stehen: 
- Körper: (zB) Hochgewachsen
- Geist: Langsam  
  etc.

Oder meinst du, es ist ein Problem, weil derselbe Beschreiber-Name sonst zweimal vorkommt, einmal bei Körper und einmal bei Geist? 
Dabei fällt mir gerade auf, wieso wir das diskutieren: ich hab in meiner Kurzliste gar kein Slow bei Mind, sondern nur eins bei Body. Ist auch im Originaltext nicht da. Das hat er wohl vergessen - ist auch nicht das erste Mal, ich hab noch ein paar mehr Wörter aus dem Anhang vorne in die Kurzliste reinkopiert, weil ich es für einen Versehen hielt.

**Comment by thopanX** [comment]
Wegen Slow hast du recht. Nö, ich seh das nicht als Problem mit der Doppelnennung.

**Comment by thopanX** [comment]
Bin durch. An Stellen mit [XXX] fiel mir keine gute Übersetzung ein.
