### ISSUE TITLE
Kapitelübersetzungen untereinander aufteilen?

### ISSUE THREAD

**Issue by schlawiner** [schlawiner/fu-rpg-frei-und-universell#12]
Wie wollen wir denn weiter vorgehen - macht jeder ein eigenes Kapitel, vielleicht abwechselnd, und der andere überarbeitet es jeweils? Wenn ja, wer macht welche Kapitel, damit es ungefähr gleich viel ist?

**Comment by thopanX** [comment]
Soweit ich es überblicke, sind Kapitel 1 und 2 zumindest rohübersetzt. Was mir auffällt, ist, dass die restlichen Artikel den französischen Text zum Übersetzen drin haben, das hilft mir leider gar nicht. Da wäre es vielleicht gut, wenn wir beide von der englischsprachigen Variante aus arbeiten würden. Ansonsten würden wir vermutlich zwei unnötig (leicht) abweichende Übersetzungen bekommen, was mehr Arbeit macht.

Wie wäre es, wenn du im Master die englischsprachigen Texte (mit) einpflegst, meinen Zweig löschst und ihn dann neu erstellst? So hätten wir dieselbe Basis, ich würde die französischen Passagen in meinem Zweig dann einfach löschen.

Um einfach mal was vorzuschlagen, könnte ich die Kapitel fünf, sechs, sieben machen. Du hast ja mit Kapitel eins und zwei schon vorgearbeitet, und wir hätten dann größere Blöcke und kein abwechselndes Gewusel. Meinung?

---

1 Einleitung
2 Die Grundlagen
3 Die Figuren
4 Action
5 Erzähler/in
6 Auf der Suche nach dem Tempel von Toth
7 Anhang

**Comment by schlawiner** [comment]
Die Aufteilung 1-4 Tina, 5-7 Thorsten klingt gut, machen wir es so. 
Das Einfügen der englischsprachigen Texte mache ich, das ist kein Problem und wollte ich im Laufe der Zeit auch für mich machen (Hauptbasis ist schon das Original, der franz. Text ist nur eine Hilfe und Inspiration bei Unklarheiten für mich). 

Ich kopierte den Text dafür bisher einfach aus dem pdf heraus und in mein Markdowndokument hinein, aber ich habe gemerkt, dass neben den unschönen Zeilenumbrüchen, die aber egal sind, da manchmal Kapitälchen oder andere Sonderzeichen verlorengehen. Du hast doch auch schonmal den Text extrahiert, ist das bei dir auch so? Wenn nicht, könnten wir ja deinen "Extrakt" zum Hineinkopieren benutzen.

Ich lege dann nach dem Einkopieren des engl. Textes einen neuen Branch für dich an, einverstanden. Irgendwelche Namensvorlieben dafür?

Was das Herauslöschen des französischen Textes in deinem Branch angeht, befürchte ich, dass das beim späteren mergen der Branches da Probleme geben könnte. Ich hätte bei der späteren Durchsicht auch gerne beide Versionen noch drin, falls ich mal was prüfen will. Normalerweise kommentiere ich schon übersetzte Textteile (beider Sprachen) in Markdown aus, mit . 

Macht es dir was aus, den französischen Text in deinem Branch drinzulassen? Vielleicht reicht es ja, sie so wie ich das mache, auszukommentieren.

**Comment by thopanX** [comment]
Das mit dem Mergen hatte ich nicht bedacht, dann lassen wir den französischsprachigen Teil drin und kommentieren den aus, joh.

Der Name des Zweigs ist mir echt wumpe ^^ von mir aus wieder mein Vorname?
