### ISSUE TITLE
Zeitplanung?

### ISSUE THREAD

**Issue by thopanX** [schlawiner/fu-rpg-frei-und-universell#13]
Mir geht es nicht um einen starren Plan, nur um eine grobe Vorstellung, wann du die Übersetzung im Ganzen fertig haben möchtest. Eine Monatsangabe würde mir schon reichen.

Ich könnte mir dann innerhalb des zeitlichen Rahmens überlegen, wie ich mich einteile. Was meinst du?

**Comment by schlawiner** [comment]
Puh, darüber hab ich noch gar nicht nachgedacht, ich hab vorher immer nur mal so in den Pausen zwischen meinen Pomodoros dran gearbeitet. Wie lange das dauern würde, kann ich nicht genau sagen, aber wie wäre es mit spätestens Ende Juni? Oder ist das zu lang? Ende Mai würde ich sicher auch schaffen, und wäre vielleicht auch motivierender, weiß nicht. Was meinst du?

**Comment by thopanX** [comment]
Ende Juni klingt super, da ist dann noch genügend Zeit, ohne dass wir in Stress geraten.
