### ISSUE TITLE
Englische Texte in Kapitel 3-7 einkopieren

### ISSUE THREAD

**Issue by schlawiner** [schlawiner/fu-rpg-frei-und-universell#14]

**Comment by schlawiner** [comment]
Bin grade dabei, aber es dauert bei den vielen Tabellen under Absätzen im Beispielabenteuer etwas länger. Wird aber bis heute mittag fertig, denke ich.

**Comment by thopanX** [comment]
Okidoki, lass dir Zeit, bin gleich eh für den Rest des Tages weg.

**Comment by schlawiner** [comment]
Erledigt (für deine Kapitel), deinen alten (eh noch quasi unbenutzten) Branch gelöscht und gleichnamigen Branch neu angelegt.
