### ISSUE TITLE
Gemeinsame Konventionen

### ISSUE THREAD

**Issue by thopanX** [schlawiner/fu-rpg-frei-und-universell#15]
Hier mal eine Übersicht zu wichtigen Dingen, die mensch im Kopf haben sollte. Einiges davon sind gleich Fragen an dich, die wir hier klären können.

Ergänzungen gern in die Kommentare, ich aktualisiere die Wikiseite dann..
- durchgängig weilbliche Schreibweise, zum Beispiel "Spielerin", "Erzählerin", …
- immer darauf achten, in welchem Zweig mensch gerade ist
- generell Singular, außer mal kontexbezogen Plural
- Anredeform ist "du"

**Comment by schlawiner** [comment]
Singular vs Plural: Teilweise ist tatsächlich "ihr" gemeint (eher selten, und man erkennt das dann schon aus dem Kontext), aber ich denkegrundsätzlich sollte es fast in allen Fällen "du" sein, da man ja ein Buch wie dieses eher als Einzelperson liest.

Ich bin auch für kleines "du", die Briefanrede finde ich immer etwas gestelzt.

**Comment by thopanX** [comment]
Ich übertrag das später ins Wiki, sonst haben wir einen ähnlichen Fall wie vormals, nur andersherum. ^__^

**Comment by schlawiner** [comment]
Weitere Dinge zum Abgleichen:
- Liste der Deskriptoren zwischen Kapitel 3 (Figuren) und Anhang
- Deskriptoren und Konzepte der Beispielfiguren in Kapitel 3 und Kapitel 6 (Beispielabenteuer), wo sie teilweise wieder auftauchen

**Comment by schlawiner** [comment]
- Das Wort **Descriptor** - ich tendiere inzwischen zu **Beschreiber**. 
  Denn "Descriptor" ist auch auf Englisch ein eher technisches Wort, dass man aber trotzdem verstehen kann, wenn man es nicht kennt, weil "description" drin steckt, und gleichzeitig zeigt es an, dass es sich nicht einfach um eine allgemeine Beschreibung sondern ein spezifisches Spielelement handelt. 
  Auf deutsch liegt es nahe, das ähnlich zu machen. Beschreiber ist ein komisches Wort, aber jeder kann leicht ableiten, dass es beschreibend wirken soll, und zusätzlich kann man es wegen seiner leichten Fremdartigkeit nicht so leicht im Textfluss mit etwas anderem Verwechseln. "Beschreibungen" wäre da zB etwas kritisch, weil es eben auch als allgemeines Wort existiert und hier soll es ja etwas sehr spezifisches sein.

**Comment by thopanX** [comment]
Um mir da eine Meinung zu bilden, wird es ein bisschen dauern, deshalb tendiere ich dazu, (erst mal) deine Übertragung zu nehmen.

Mir stößt das Wort vom Sprachgefühl her ziemlich auf und ich bin hin- und hergerissen, wie ich es finden soll.

**Comment by thopanX** [comment]
Hab die Diskussion zu "Descriptor" mal ausgelagert, so muss mensch immer suchen.
