### ISSUE TITLE
Wortspiel "beating the odds"

### ISSUE THREAD

**Issue by thopanX** [schlawiner/fu-rpg-frei-und-universell#2]
"Wahrscheinlichkeit zu überwinden"/"nicht krumm zu sein"

Anmerkung der Übersetzerin: Der Autor macht hier ein Wortspiel - die Aussage "beating the odds" bezieht sich normalerweise darauf, etwas entgegen aller Wahrscheinlichkeit zu schaffen. Das Wort "odd" bedeutet aber auch _ungerade_ Zahlen als Gegenteil von _gerade_ und bezieht sich im Spiel auf ungerade Würfelwerte (1,3,5), die hier für schlechte Würfe stehen.

**Comment by schlawiner** [comment]
Ich hab da schon hin- und herüberlegt, und das beste, was mir bisher eingefallen ist, ist was mit "krumm" wie krumme Zahlen. Habe aber immer mehr das Gefühl, dass das nur "mein" Wort ist und es sonst keiner für ungerade Zahlen verwendet ausser mir 😨 . 
Oder eben umgekehrt, etwas was "gerade" mit gut verbindet. "gerade stehen", "gerade gewinnt", "gerade Glück gehabt", ...?
Der französische Übersetzer nimmt übrigens einen Satz, der "keine Ungeschicklichkeit (Patzer?) machen" nahekommt. Impair heisst auf französisch als Adjektiv ungerade und als Substantiv "Missgeschick". Ob sich sowas auch auf deutsch findet? Vielleicht nicht wörtlich, aber vielleicht etwas, was zumindest ähnlich klingt...Synonyme wäre zB auch Fauxpas, Fehltritt, Patzer, ...

**Comment by thopanX** [comment]
Ich bin inzwischen bei "die ungerade Zahlen vermeiden", denn praktisch soll man keine ungeraden Zahlen würfeln, weil sie Misserfolg darstellen. Ich finde, dass wir uns mit der Übertragung keinen abbrechen sollten. Redewendungen kann man halt nicht immer direkt übertragen

Wenn du das Wort "krumm" verwenden willst, was ich auch kenne, von mir aus kein Problem. Es sollte nur zum Ton des Rests des Textes passen.

**Comment by schlawiner** [comment]
Ok, ich nehme "ungerade Zahlen vermeiden" und lasse dann die dazugehörige Fußnote komplett fallen, weil sie ohne Wortspiel nicht mehr nötig ist.
