### ISSUE TITLE
Wollen wir das Überarbeiten der Kapitel umgekehrt machen zum Übersetzen?

### ISSUE THREAD

**Issue by schlawiner** [schlawiner/fu-rpg-frei-und-universell#24]
Wollen wir es so machen, dass jeder die Kapitel des Anderen nochmal durchgeht und Korrekturen vorschlägt und diskutiert?
Wenn ja, assigne ich die Todos/Issues dafür (im Überarbeitet-Milestone) jeweils entsprechend. 
Natürlich kann und sollte man auch schon vorher seine eigene Übersetzung nach ein paar Tagen noch mal durchgehen und Überarbeiten, wie du das schon angesprochen hast.
Zuletzt schlage ich noch eine weitere Runde Korrekturlesen (siehe Milestone dazu) vor, wie wir das assignen können wir ja noch sehen. (Vielleicht finden wir noch ein paar Unbeteiligte, die auch nochmal drübergucken.)

**Comment by thopanX** [comment]
Ja, gute Idee mit dem Wechsel.
