### ISSUE TITLE
Wide but narrow

### ISSUE THREAD

**Issue by thopanX** [schlawiner/fu-rpg-frei-und-universell#25]
Es geht um einen Deskriptor der Gou-Zou-Brücke im Abenteuer.

"Breit aber schmal" kommt mir komisch vor oder kann es sein, dass damit gemeint ist, dass die Brücke zwar breit ist, aber bei Problemen aber immer noch zu schmal sein ḱann?

**Comment by schlawiner** [comment]
Ich glaube die Brücke ist halt ziemlich lang, weil sie das Tal durchspannt? Das war mein erster Gedanke, als ich das las. Aber beim zweiten Hinsehen - ist es vielleicht doch anders gemeint. Hm. 

Es ist ja eine "single iron girder railway bridge" - also nur diese eine Brücke gibt es, und sie ist eine Eisenträger-Eisenbahnbrücke. Die sind ja meistens ohne Fußweg, also muss man entweder auf den Schienen laufen oder ... am Rand, wo eigentlich kein Platz für einen Menschen ist. 
Kein Problem, wenn kein Zug kommt, aber man soll ja auf jeden Fall einen kommen lassen. Vielleicht ist es so gemeint! 
Solange kein Zug da = breit, wenn Zug da: doch etwas schmal und eng, da man von den Schienen muss und an den Rand springen?
