### ISSUE TITLE
Roll of quarters

### ISSUE THREAD

**Issue by thopanX** [schlawiner/fu-rpg-frei-und-universell#26]
Schwierig: einserseits tatsächlich eine Geldrolle, andererseits als Totschlägerersatz benutzt

**Comment by schlawiner** [comment]
Interessant, hatte mir zu der ominösen Rolle Münzen noch gar keine Gedanken gemacht. Ich denke, wer das auf englisch liest, weiß entweder, was man als Boxer mit einer Rolle Münzen NOCH machen kann, oder auch nicht (die meisten Leute wohl sogar eher nicht). Und auf deutsch wäre das auch nicht anders. Auch im deutschsprachigen Raum wird in Kampfsportforen über die Nützlichkeit einer Münzrolle als Faustschutz/Schlagkraftverstärker diskutiert, es ist also nicht komplett unbekannt (wenn auch unbekannter als im englischsprachigen Raum).

**TL;DR:** kann man es nicht einfach so auf Deutsch übersetzen, **Münzrolle**, und es dabei belassen - wer es versteht, macht was draus, die anderen nicht (so wie wahrscheinlich auch auf Englisch)?
In der französichen Übersetzung ist die Doppelnutzung übrigens komplett fallengelassen worden - jetzt trägt er nur noch "Dix dollars en petite monnaie" bei sich, zehn Dollar als Kleingeld. Da wäre die Münzrolle auf jeden Fall die bessere Wahl, wenn vielleicht auch nicht perfekt!

**Comment by thopanX** [comment]
"Münzrolle" es ist. Danke dir.
