### ISSUE TITLE
Übersetzung für "Descriptor"

### ISSUE THREAD

**Issue by thopanX** [schlawiner/fu-rpg-frei-und-universell#27]
**schlawiner:** Das Wort Descriptor - ich tendiere inzwischen zu Beschreiber. Denn "Descriptor" ist auch auf Englisch ein eher technisches Wort, dass man aber trotzdem verstehen kann, wenn man es nicht kennt, weil "description" drin steckt, und gleichzeitig zeigt es an, dass es sich nicht einfach um eine allgemeine Beschreibung sondern ein spezifisches Spielelement handelt. Auf deutsch liegt es nahe, das ähnlich zu machen. Beschreiber ist ein komisches Wort, aber jeder kann leicht ableiten, dass es beschreibend wirken soll, und zusätzlich kann man es wegen seiner leichten Fremdartigkeit nicht so leicht im Textfluss mit etwas anderem Verwechseln. "Beschreibungen" wäre da zB etwas kritisch, weil es eben auch als allgemeines Wort existiert und hier soll es ja etwas sehr spezifisches sein.

**Comment by thopanX** [comment]
Ich mag das Wort "Beschreiber" überhaupt nicht. Es existiert zwar in der Sprachwissenschaft, aber nicht in der Alltagssprache, was ich hier schwierig finde.

Mir fällt allerdings auch aktuell nichts Besseres als "Deskriptor" ein, auch wenn das keine wirkliche Übersetzung ist.

**Comment by schlawiner** [comment]
Dass er eben nicht in der Alltagssprache vorkommt, aber trotzdem auch für Laien und ältere Kinder völlig klar ist, empfinde ich als Vorteil. Dann kann man ihn nicht mit Beschreibung verwechseln (die ja auch im Text vorkommt) und merkt: das ist ein besonderes Wort, das etwas mit der Spielmechanik zu tun hat.

Deskriptor hat zwar den ersten Vorteil (ist nicht in der Alltagssprache), aber nicht den zweiten, dass die Bedeutung trotzdem klar ist.

Als Alternative fällt mir noch Kennzeichner/Kennzeichnung ein, oder vielleicht noch Etikett, Kennwort, Stichwort, Schlagwort?

**Comment by thopanX** [comment]
Nehmen wir Beschreiber.
