### ISSUE TITLE
Character = Charakter/(Spiel-)Figur?

### ISSUE THREAD

**Issue by thopanX** [schlawiner/fu-rpg-frei-und-universell#28]
Ich hatte aus der Gewohnheit heraus "character" mit "Charakter" übersetzt, erinnerte mich dann aber an deinen Einrtag im Wiki, wo "Figur" steht. Ich hab dann begonnen, im Abenteuer "Charakter" durch "Figur" zu ersetzen und merkte, dass das für mich nicht passt.

Ich bin dafür, dass wir den eingeführten und stehenden Begriff "Charakter" verwenden, was meinst du?

**Comment by schlawiner** [comment]
Oh, weh, was ich dazu meine. Dieses Wort ist ein kleines Steckenpferd von mir. Ich habe mir da schon länger drüber Gedanken gemacht und sehe das ganze etwas anders. "Charakter" klingt vielleicht für jemanden, der vorher schon Rollenspieler war, normal. Aber wir wollten ja inklusiver sein und auch Leute, die kaum Rollenspielerfahrung haben, das Buch verstehen lassen. 

Mal abgesehen davon kratzt das Wort "Charakter" bei mir in dem Zusammenhang einfach wie Fingernägel auf einer Tafel - es ist einfach falsch, ein "false friend". Die deutsche Übersetzung ist eindeutig  "Figur" und so auch verständlicher für Neulinge und trotzdem noch nachvollziehbar für alte Hasen. 
Siehe auch den Wikipedia-Artikel für [Nicht-Spieler-Charakter](https://de.wikipedia.org/wiki/Nicht-Spieler-Charakter) - "ist eine Klasse von Figuren, die in bestimmten Arten von Spielen verwendet wird. Die deutsche Übersetzung ist ein falscher Freund, korrekt wäre Nicht-Spieler-Figur."

**Comment by schlawiner** [comment]
Wenn wir uns wirklich nicht einigen können, können wir ja zwei Versionen generieren, indem wir am Ende alle Fälle von Figur  durch Charakter ersetzen. Links für beide Versionen anbieten sollte ja später kein Problem sein. Da kann sich jeder runterladen, was er mag. Und ich schicke meiner 11jährigen Nichte die Version mit "Figur" auf ihr Handy zum Lesen und mit Oma und Freundinnen zu spielen ;).

**Comment by thopanX** [comment]
Das Argument der Inklusion finde ich hier ein bisschen schwierig, in Rollenspielen wird, organisch gewachsen, nicht von "Figuren" gesprochen, sondern von "Charakteren", das ist ein eingeführter Begriff. Ob er rein sprachlich nicht ganz zutrifft oder nicht, wir kommen da an der Realität nicht vorbei, denke ich. Ich möchte das übrigens ganz deutlich von der Gendering-Angelegenheit abgrenzen, wo wir die Realität ganz bewusst ändern wollen – muss das beim Begriff "Charakter" auch sein? Ich finde nicht. 

Ich bin da zwiegespalten. Einerseits finde ich schon, dass man auch mal Dinge "einfach anders machen" kann, andererseits muss das für mich dann aber auch sinnig sein und in diesem Fall liegt mir das zumindest gerade etwas quer.

Die letztliche Entscheidung überlasse ich dir, ich werd mit beiden Varianten leben können und fände zwei Versionen unnötig.

**Comment by schlawiner** [comment]
Ich bin auch zwiegespalten.
Einerseits weiß ich, dass es keinen Sinn hat, Sprachentwicklungen aufhalten zu wollen, weil Sprachen immer im Fluss sind. 
Und ich weiß auch, dass fast alle, die diese Übersetzung in ihrer digitalen Form _finden_ werden, **schon geübte Rollenspieler** sind, die die Verwendung von _Figur_ statt _Charakter_ etwas befremdlich finden werden. 

Andererseits möchte ich aber auch das Buch, und damit das Rollenspielen, **für Neulinge** so zugänglich wie möglich machen. Und _Charakter_ in diesem Zusammenhang ist nun mal für solche Leute erstmal missverständlich und macht das Lesen und Einsteigen daher auf jeden Fall nicht einfacher. 
Leider weiß ich auch, dass a) die wenigsten Neulinge auf FU und unsere Übersetzung stoßen werden. Dafür bewegen wir uns einfach nicht im richtigen Umfeld - wer sich auf Google+ in Rollenspielgruppen rumtreibt, ist selten Neuling. 
Und b) weiß ich auch, dass das FU-Regelbuch nicht als erstes Rollenspiel für komplette Neulinge dienen _kann_, auch wenn es das gerne würde. Dafür setzt es einfach zu viel voraus und sagt zu wenig dazu, wie man Erzählerin ist und _was genau_ sie macht. Das weiß ich so gut, weil es mir selber, als vor Kurzem selbst noch blutigem Neuling nicht annähernd gereicht hätte, auch nicht für Freiformspiel. Vorher musste ich noch einige andere Spielregeln in die Richtung (besonders Dungeon World und Apocalypse World) lesen und Videos anschauen und in dem ein oder anderem Spiel selber als Spielerin mitspielen.

Trotzdem fände ich es schön, wenn die wenigen Neulinge, die unsere FU-Übersetzung finden (oder von mir nach einer Anfix-Session geschenkt bekommen ;)), vielleicht schon mal bei einem Spiel mitgemacht haben und es jetzt mal selbst versuchen wollen, es etwas einfacher gemacht bekommen. Jedes bisschen hilft, auch klarere Formulierungen, die man als Laie versteht und über die man nicht immer wieder stolpert.

Vielleicht läuft es am Ende doch auf eine zweite "Einsteigerversion" hinaus, die ich vielleicht für private Zwecke generiere. Oder für Rollenspielfreunde, die ihr Hobby an andere Neulinge weitergeben wollen. 

Zuerst bin ich dafür, dass jeder einfach so weitermacht wie bisher und wie es ihm/ihr am besten liegt, und wir die Sache am Ende durch Suchen & Ersetzen oder reguläre Ausdrücke vereinheitlichen, in beide Richtungen.

**Comment by thopanX** [comment]
Ich versteh deine Argumentation. Im Übersetzungsprozess aber zwei Versionen zu pflegen, finde ich unnötig kompliziert und ist fehleranfällig.

Ich hab diese Woche Zeit und gehe gleich mal durch meinen Text und ändere es in deine Richtung. Wenn ich dann später tatsächlich eine eigene Version brauchen sollte, kann ich das immer noch machen.
