### ISSUE TITLE
Wollen wir zur Bearbeitung Zweige verwenden?

### ISSUE THREAD

**Issue by thopanX** [schlawiner/fu-rpg-frei-und-universell#3]
Falls ja, kannst du mir bitte die Rechte dafür geben oder jeweils einen Zweig für mich anlegen?

Ich hab vorhin versucht, einen Zweig zu erstellen, passiert aber nichts.

**Comment by schlawiner** [comment]
Ja, das können wir gerne machen, allerdings hab ich mit branches auch noch nicht allzuviel Erfahrung. 
Ich habe leider auch keine Möglichkeit gefunden, dir die Brancherstellung zu erlauben. Ich versuch das morgen mal von meinem anderen Computer aus über die Konsole.
