### ISSUE TITLE
Css-Stylesheets für epub anpassen

### ISSUE THREAD

**Issue by schlawiner** [schlawiner/fu-rpg-frei-und-universell#36]
Gitbook kann so wie es ist nicht besonders viel Layout. Wir sprechen in der Einleitung aber davon, dass die Sidebars/Seitenleisten mit Tipps dreispaltig gehalten sind. Ich habe mal angefangen, das per CSS umzusetzen, aber das klappt nicht in allen Modalitäten. Das pdf ignoriert jedes Styling, die Webversion zeigt eigentlich nur Hintergrundfarben an und keine Spalten, und bei epub geht das mit den spalten zwar, sieht aber schrecklich aus, weil oben und unten alles abgeschnitten wird.
Entweder entferne ich den Hinweis auf die Spalten aus dem Text oder ändere ihn auf etwas, was tatsächlich per CSS machbar ist, oder ich krieg's noch hin. Mal sehen.
Das pdf sieht grundsätzlich nicht besonders hübsch aus, da muss ich vielleicht auch noch etwas dran schrauben.

**Comment by thopanX** [comment]
Ich hab die aktuelle EPUB-Version mal in meinen tolino geladen und finde, dass das schon super ausschaut – Spaltensatz sehe ich da aber nicht. Ich denke, dass wir die Zusatzinfo auch unter horizontalen Linien (--- in Markdown) platzieren können und nicht unbedingt den dreispaltigen Satz brauchen.

Wenn du daran basteln willst, cool; wenn nicht, alles gut.

**Comment by schlawiner** [comment]
Oh, das muss ich auch mal probieren - ich hab auch einen Tolino, na sowas! Komisch, dass iBooks auf dem Mac die Spalten im Epub zeigt. Anscheinend ist iBooks sowieso der so gut wie einzige Reader, der CSS3 kann. Tolino und co können nur CSS2, wo es noch keine Spalten gibt. Nun gut.

**Comment by schlawiner** [comment]
Ich denke für das ePub mache ich Sidebars in Form von abgesetzten Kästen, ähnlich wie beim ePub von Archipelago. Ich habe mal ein Probe-ePub (aus Pandoc) damit ins git hochgeladen, siehe fu.epub.

**Comment by schlawiner** [comment]
Habe die Blockquotes (Spielbeispiele) im Epub mal angepasst, damit sie ähnlich aussehen wie in der Vorlage aus The Warren.  
Bei den Sidebars bin ich noch nicht sicher. Bisher habe ich einfach hervorgehobene Kästen. Vieleicht lass ich das, falls mir nichts besseres einfällt.
