### ISSUE TITLE
Website (GithubPages) für HTML-SRD updaten

### ISSUE THREAD

**Issue by schlawiner** [schlawiner/fu-rpg-frei-und-universell#40]
Ich bin im Laufe der Zeit immer unzufriedener mit Gitbook geworden. Die Vorschlagfunktion für Korrektur und Lektorierung finde ich immer noch gut und möchte sie auch gerne weiter benutzen.

Aber der Export in die Ausgabeformate ist mir etwas zu beschränkt. 

Ich tendiere inzwischen, lieber Pandoc für den Export zu benutzen. Gerade das Webdokument in html, das Gitbook erstellt, ist ein Problem - man kann es nur bei gitbook hosten und nicht an beliebiger anderer Stelle. Man kriegt seine Daten nicht dort weg! Gar nicht gut. 
Außerdem sind die verwendeten Stylesheets sehr intransparent, es ist schwer, Änderungen daran zu machen, um das Aussehen anzupassen.

Ich werde also ein paar **CSS-Stylesheets anlegen** bzw erweitern: 
Einerseits eins für die **HTML-Darstellung in Form eines SRD**, inspiriert von http://srd.faterpg.de/index.php/fate-core/ und https://jcgames.de/lite/rollenspiel/.

**Comment by schlawiner** [comment]
Inzwischen denke ich, ich werde eine (wie mein Blog) auf Hugo basierende Website mit dem [Material-docs-Theme](http://themes.gohugo.io/material-docs/) umzusetzen - mit geänderten Farben. Hugo nimmt nativ Markdown für den Content.

**Comment by schlawiner** [comment]
Test der SRD-Seite: http://schlawiner.github.io/fu-rpg-frei-und-universell/02-grundlagen/

Noch zu tun nach Fertigstellung der letzten Version (nach Feinkorrektur)
- [x] Texte der Kapitel in die index.md-Dateien in die entsprechenden content-Folder im hugo-Branch einfügen
- [x] existierende Kapitel updaten mit den Korrekturen
- [x] Schriftgrößen anpassen (die sind am Desktop irgendwie sehr klein)
- [x] Tabellen anpassen, besonders in den Sidebar-Blöcken schlecht lesbar durch dunklen Hintergrund
- [x] Anpassen: Tags und Kram von Pandoc entfernen ({unnumbered})
- [x] Impressum verlinken

**Comment by thopanX** [comment]
Sieht auf den ersten Blick sehr geil aus.
