### ISSUE TITLE
Latex-Stylesheet für PDF-Export anpassen

### ISSUE THREAD

**Issue by schlawiner** [schlawiner/fu-rpg-frei-und-universell#41]
Auch das von Gitbook ausgegebene PDF finde ich nicht besonders hübsch (es scheint über den Umweg html nach pdf exportiert zu werden) und auch schwer anzupassen. 

Für den Export per Pandoc in ein Buch im PDF-Format werde ich die **Latex-Template**, die ich schon vor einer Weile angelegt habe, anpassen, damit ein schickeres Buch herauskommt.

**Comment by schlawiner** [comment]
Inspiration: Das Layout von Nipajin http://ludus-leonis.com/nipajin/, das ebenfalls in Latex gemacht ist und unter CC-Lizenz auf Github zu finden ist.

**Comment by schlawiner** [comment]
Ich habe ein paar Sachen von Nipajin geklaut, weil ich null Ahnung habe, wie man damit mehr als eine Standard-Hausarbeit layoutet. Hier mal ein [Beispiel, wie es inzwischen aussieht - Kapitel 2.](https://dl.dropboxusercontent.com/u/13207548/Spiele/fu-de-latex-sample.pdf)

**Comment by thopanX** [comment]
Das sieht doch schon nice aus.

**Comment by schlawiner** [comment]
Ok, wir machen es nun doch mit Scribus, daher schließe ich dieses Issue.
