### ISSUE TITLE
Letzte Korrekturhinweise

### ISSUE THREAD

**Issue by thopanX** [schlawiner/fu-rpg-frei-und-universell#46]
Dinge, die mir beim Durchlesen der SRD noch aufgefallen sind.

**Comment by thopanX** [comment]
https://fu-rollenspiel.de/03-figuren/

> Sobald du weisst, in welcher Spielwelt und unter welchen Voraussetzungen euer Abenteuer stattfindet, kannst du dir langsam Gedanken über deine Figur machen - über ihr „Konzept“. Dies ist der Kern deiner Figur und beschreibt, was sie ausmacht und wer sie ist. Ein Konzept lässt sich in wenigen Worten oder einem kurzen Satz zusammenfassen.
> Das Konzept kann den Hintergrund oder den Beruf deiner Figur beschreiben, wie „Paranormaler Ermittler“ oder „Wunderkind“. Oder es gibt Aufschluss über ihre Persönlichkeit, wie „Edler Wilder“ oder „Verrückter Professor“.
> Das Konzept deiner Figur sollte natürlich zur Spielwelt, zum Hintergrund und zur Art der Abenteuer passen, die ihr spielt. Ein „Gewiefter Bulle“ passt vielleicht nicht ganz ins mittalterliche England, aber ein „Welterfahrener Schultheiß“ könnte hier genau das Richtige sein. Lass dich beim Konzept deiner Figur von der Spielwelt inspirieren!

--> Abstand Absätze erhöhen, jeweils Zeile einfügen

**Comment by thopanX** [comment]
> Szenen sind die Grundbausteine der Geschichte und können beliebig lange Zeiträume von wenigen Sekunden bis hin zu vielen Stunden abzubilden

--> abbilden

**Comment by schlawiner** [comment]
Das erste gefixt, das zweite hatte ich schon neulich gefunden und gemacht - vielleicht noch eine alte Version im Cache?
