### ISSUE TITLE
Rohübersetzung Kapitel 4 Aktionen ("Etwas tun")/Actions

### ISSUE THREAD

**Issue by schlawiner** [schlawiner/fu-rpg-frei-und-universell#8]

**Comment by schlawiner** [comment]
Mit dem ersten Durchgang bin ich durch, uff!
Ich lasse das ganze noch ein paar Stunden ruhen und gehe nochmal drüber und schließe dieses Issue. 
Dann kannst du für Überarbeitungen entweder die Vorschlagsfunktion bei gitbook benutzen oder ich mache bei Bedarf einen neuen Branch auf.

**Comment by thopanX** [comment]
Vorschlagsfunktion find ich gut, da ich das schon aus Google-Docs-Dokumenten kenne und gut finde. Wenn ich die Benachrichtigung bekommen habe, geh ich ran.
